version: "3"
services:
  ray:
    image: rayproject/ray:1.12.2-py36-gpu
    volumes:
      - ./tmp/ray-logs:/tmp/ray
    ports:
      - 10001:10001
      - 8265:8265
    command: bash -c " ray start --head --dashboard-host 0.0.0.0 --num-cpus=8 --num-gpus=1 --include-dashboard true && ray status && serve start -n default  --http-host 0.0.0.0 --http-port 8000 --http-location EveryNode && tail -f /dev/null "
